### PR TITLE
[BUGFIX] use bootstrap collapsible with correct element selectors

### PR DESCRIPTION
**Pull request by yeldiRium**
This is a re-open of #448 after rebasing onto newest master and finally testing the contained changes.

### CODE REVIEW

**Comment by dmh** [comment]
Hey @yeldiRium 

What about if we will use `<a>` tag instead of `<button>`?
With `<a>` we can keep existed styling and fix the issue, but if we will use `<button>` - we need to fix CSS styling to make button looks like a link.

```
<a
role="button"
class="{f:if(condition: data.pi_flexform.data.columns.lDEF.expanded.vDEF, then: '', else: 'collapsed')}"
data-toggle="collapse"
href="#collapse-{data.uid}"
data-parent="#group-{data.tx_gridelements_container}"
aria-expanded="{f:if(condition: data.pi_flexform.data.columns.lDEF.expanded.vDEF, then: 'true', else: 'false')}">
{data.header}
</a>
```

**Comment by websi** [comment]
This does not work with an html [base](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) tag. 
Within TYPO3 you can configure this behaviour with [config.baseurl](https://docs.typo3.org/typo3cms/TyposcriptReference/8.7/Setup/Config/#baseurl)

**Comment by dmh** [comment]
Hi @websi,

What is your suggestion, use `<button>` tag, or?

**Comment by yeldiRium** [comment]
Using the `button` tag and adjusting the styles is the safest option.
An `a` tag will lead to the start page if javascript is disabled.

It might be possible to use the `a` tag if we generate an absolute url including the section, but then the javascript relying on the `href` attribute probably won't work anymore.

**Comment by dmh** [comment]
Hey,

Not really safest if we are talking about backward compatibility. We have a lot of sites on t3kit which are using custom styles for Collapsible element, and tag `button` instead of `a` could cause problems if we will update those site to the last version.

We decided to keep compatibility instead of correct behavior in case of disabled JS.

In t3kit9 we will use buttons.

Thanks for help

**Pull request closed without merging**
