### PR TITLE
[FEATURE] html and image additional compress

### PR DESCRIPTION
**Pull request by anjeylink**

### CODE REVIEW

**Comment by anjeylink** [comment]
fixes #386 
1. By default image compression extension is not installed.
2. Make sure all JS is in footer.
3. Display inline css as inline.
4. Compress html of body.

**Comment by websi** [comment]
Should this moved to Repo [t3kit/t3kit](https://github.com/t3kit/t3kit)?
Not every system has installed all needed tools for [pxa_images_compressor](https://github.com/pixelant/pxa_images_compressor).
Not every project want to compress the html by TYPO3. This can be done by the web server for example.

**Comment by anjeylink** [comment]
@websi yes, you are right, i'll move it to t3kit. Also i have added condition if html_compress is installed which will make it optional to use

**Comment by dmh** [comment]
0376bdaf2d82f4a6ab5204d6d13891a610666412

**Pull request closed without merging**
