### PR TITLE
[FEATURE]: add additional backend areas for footer quick links, copyright and bottom navigation

### PR DESCRIPTION
**Pull request by aennafae**

### CODE REVIEW

**Comment by pixelmatseriks** [comment]
I'm not really sure about the need of additional backend areas in footer, is there a specific reason why you need these? We used to have more areas in footer, but we realized that we very often had to modify it per project. Now when it is just one area, it is easy to customize the footer according the design directly in BE.

**Comment by aennafae** [comment]
It's an other solution for setting the footer classes not manually. Resulting from this https://github.com/t3kit/theme_t3kit/pull/285 PR

**Comment by pixelmatseriks** [comment]
Aha, then I understand what you want to achieve. I checked the footer, and noticed that all the "rows" have classes for the columns, so in this case we would need six footer areas. If we split the footer to these areas, we would lose the ability to change appearance of the footer directly from the BE without changing templates and/or typoscript. Maybe a solution could be to create a new gridelement "footer" CE, with the structure and classes of the current foot with six content areas in it? I believe it would also make it possible to limit what CE:s that can be placed in each content area of the "footer" CE.

**Comment by aennafae** [comment]
I think we should try the LESS solution, suggested by Dmytro, to handle this issue. Will you modify footer.less files in order to use it without the special classes or should we create a PR?

**Comment by aennafae** [comment]
Will be solved in https://github.com/t3kit/theme_t3kit/pull/303

**Pull request closed without merging**
