### PR TITLE
[FEATURE] Change Login label (Podio Feature_5)

### PR DESCRIPTION
**Pull request by danetkrueng**

### CODE REVIEW

**Review by dmh — CHANGES_REQUESTED** [review]
According to Podio, we need to add some manual changes to t3kit page structure. So could you also add those manual changes to `t3kit_db` as pull-request with reference to this one PR.

**Comment by dmh** [comment]
@danetkrueng

**Comment by laurisaarni** [comment]
@dmh this will be continued tomorrow.

**Comment by danetkrueng** [comment]
@dmh Here is the merge request for t3kit_db updated https://github.com/t3kit/t3kit_db/pull/3

cc: @laurisaarni

**Review by dmh — APPROVED** [review]

**Pull request merged**
