### PR TITLE
[!!!][BUGFIX] synchronize extension dependencies between "composer.json" and "ext_emconf.php"

### PR DESCRIPTION
**Pull request by websi**
Move non direct dependencies to section "suggest"

### CODE REVIEW

**Comment by websi** [comment]
See discussion within pull request #267

**Comment by websi** [comment]
Issue for any other dependencies for optional features. #277

**Comment by websi** [comment]
Can anyone please give feedback. @dmh @pixelmatseriks @MattiasNilsson

**Comment by dmh** [comment]
@websi  Hey, we are working on next release of t3kit and this PR will be the main part of this next release.

**Comment by dmh** [comment]
@websi This is the big breaking change, and we want to have it in a separate release. 
Also, we are trying to be more structured and creating Release notes in t3kit slack channel, and in every this release note we have a part with plans for next release. The last note includes this Pull-request as a part of next release. I understand that there are many channels of communication, but if you have other suggestions just let me know. 
Thanks

**Comment by websi** [comment]
Sorry, i have not seen the part "`Next t3kit release`" at the slack channel.

Thanks for the information.

**Pull request closed without merging**
